// Soupisky klubů Tipsport extraligy pro našeptávač jmen ve formuláři. GENEROVÁNO skriptem
// skripty/stahni_soupisky.js z hokej.cz (stránky klubů → Soupiska) – neupravovat ručně.
// j = jméno a příjmení, t = tým (jako v EXTRALIGA.KONFIG.TYMY), p = pozice (B brankář, O obránce, U útočník).
var EXTRALIGA_SOUPISKY = {
  "zdroj": "hokej.cz",
  "stazeno": "2026-09-12",
  "hraci": [
  {"j":"Dominik Frodl","t":"Karlovy Vary","p":"B"},
  {"j":"Daniel Král","t":"Karlovy Vary","p":"B"},
  {"j":"Daniel Brickley","t":"Karlovy Vary","p":"O"},
  {"j":"Kryštof Dyk","t":"Karlovy Vary","p":"O"},
  {"j":"Elmeri Eronen","t":"Karlovy Vary","p":"O"},
  {"j":"Matteo Kočí","t":"Karlovy Vary","p":"O"},
  {"j":"Pavel Kůrka","t":"Karlovy Vary","p":"O"},
  {"j":"Roberts Mamčics","t":"Karlovy Vary","p":"O"},
  {"j":"Josef Myšák","t":"Karlovy Vary","p":"O"},
  {"j":"Quinn Schmiemann","t":"Karlovy Vary","p":"O"},
  {"j":"Tobias Winberg","t":"Karlovy Vary","p":"O"},
  {"j":"Jan Bambula","t":"Karlovy Vary","p":"U"},
  {"j":"Ondřej Beránek","t":"Karlovy Vary","p":"U"},
  {"j":"Jiří Černoch","t":"Karlovy Vary","p":"U"},
  {"j":"Haralds Egle","t":"Karlovy Vary","p":"U"},
  {"j":"Vít Jiskra","t":"Karlovy Vary","p":"U"},
  {"j":"Nicholas Jones","t":"Karlovy Vary","p":"U"},
  {"j":"Filip Koffer","t":"Karlovy Vary","p":"U"},
  {"j":"Adam Lukošik","t":"Karlovy Vary","p":"U"},
  {"j":"Jakub Minárik","t":"Karlovy Vary","p":"U"},
  {"j":"Tomáš Redlich","t":"Karlovy Vary","p":"U"},
  {"j":"Robin Sapoušek","t":"Karlovy Vary","p":"U"},
  {"j":"David Šťastný","t":"Karlovy Vary","p":"U"},
  {"j":"Petr Tomek","t":"Karlovy Vary","p":"U"},
  {"j":"Matyáš Váňa","t":"Karlovy Vary","p":"U"},
  {"j":"Adam Brízgala","t":"Kladno","p":"B"},
  {"j":"Dominik Pavlát","t":"Kladno","p":"B"},
  {"j":"Jeremie Blain","t":"Kladno","p":"O"},
  {"j":"Michal Houdek","t":"Kladno","p":"O"},
  {"j":"Martin Jandus","t":"Kladno","p":"O"},
  {"j":"Michal Kempný","t":"Kladno","p":"O"},
  {"j":"Martin Matějíček","t":"Kladno","p":"O"},
  {"j":"Griffin Mendel","t":"Kladno","p":"O"},
  {"j":"Phil Pietroniro","t":"Kladno","p":"O"},
  {"j":"Adam Rulík","t":"Kladno","p":"O"},
  {"j":"Tomáš Tomek","t":"Kladno","p":"O"},
  {"j":"Tomáš Vandas","t":"Kladno","p":"O"},
  {"j":"Filip Westerlund","t":"Kladno","p":"O"},
  {"j":"Daniel Audette","t":"Kladno","p":"U"},
  {"j":"Adam Bareš","t":"Kladno","p":"U"},
  {"j":"Ondřej Bláha","t":"Kladno","p":"U"},
  {"j":"Miroslav Forman","t":"Kladno","p":"U"},
  {"j":"Nicolas Hlava","t":"Kladno","p":"U"},
  {"j":"Kelly Klíma","t":"Kladno","p":"U"},
  {"j":"Jakub Konečný","t":"Kladno","p":"U"},
  {"j":"Adam Kubík","t":"Kladno","p":"U"},
  {"j":"Oskar Lisler","t":"Kladno","p":"U"},
  {"j":"Marcel Marcel","t":"Kladno","p":"U"},
  {"j":"Niko Ojamäki","t":"Kladno","p":"U"},
  {"j":"Filip Přikryl","t":"Kladno","p":"U"},
  {"j":"Martin Procházka","t":"Kladno","p":"U"},
  {"j":"Sebastián Redlich","t":"Kladno","p":"U"},
  {"j":"Martin Ryšavý","t":"Kladno","p":"U"},
  {"j":"Samuel Vigneault","t":"Kladno","p":"U"},
  {"j":"Petr Hamalčík","t":"Liberec","p":"B"},
  {"j":"Petr Kváča","t":"Liberec","p":"B"},
  {"j":"Layton Ford Ahac","t":"Liberec","p":"O"},
  {"j":"Tomáš Galvas","t":"Liberec","p":"O"},
  {"j":"Tomáš Hanousek","t":"Liberec","p":"O"},
  {"j":"Michal Ivan","t":"Liberec","p":"O"},
  {"j":"Lukáš Kachlíř","t":"Liberec","p":"O"},
  {"j":"Radim Šimek","t":"Liberec","p":"O"},
  {"j":"Denis Zeman","t":"Liberec","p":"O"},
  {"j":"Kristaps Zile","t":"Liberec","p":"O"},
  {"j":"Martin Faško-Rudáš","t":"Liberec","p":"U"},
  {"j":"Tomáš Filippi","t":"Liberec","p":"U"},
  {"j":"Jakub Hujer","t":"Liberec","p":"U"},
  {"j":"Filip Jansa","t":"Liberec","p":"U"},
  {"j":"Radan Lenc","t":"Liberec","p":"U"},
  {"j":"Jaromír Pérez Lisa","t":"Liberec","p":"U"},
  {"j":"Adam Musil","t":"Liberec","p":"U"},
  {"j":"Adam Najman","t":"Liberec","p":"U"},
  {"j":"Servác Petrovský","t":"Liberec","p":"U"},
  {"j":"Ondřej Procházka","t":"Liberec","p":"U"},
  {"j":"Jaromír Pytlík","t":"Liberec","p":"U"},
  {"j":"Jakub Rychlovský","t":"Liberec","p":"U"},
  {"j":"Filip Sandberg","t":"Liberec","p":"U"},
  {"j":"Jaroslav Vlach","t":"Liberec","p":"U"},
  {"j":"Pavel Čajan","t":"Litvínov","p":"B"},
  {"j":"Adam Kubík","t":"Litvínov","p":"B"},
  {"j":"Matej Tomek","t":"Litvínov","p":"B"},
  {"j":"Ondřej Baláž","t":"Litvínov","p":"O"},
  {"j":"Vít Beran","t":"Litvínov","p":"O"},
  {"j":"Kevin Czuczman","t":"Litvínov","p":"O"},
  {"j":"Vojtěch Husinecký","t":"Litvínov","p":"O"},
  {"j":"Janis Jaks","t":"Litvínov","p":"O"},
  {"j":"Michal Moravčík","t":"Litvínov","p":"O"},
  {"j":"Adam Polášek","t":"Litvínov","p":"O"},
  {"j":"Petr Soušek","t":"Litvínov","p":"O"},
  {"j":"Filip Tittl","t":"Litvínov","p":"O"},
  {"j":"Jonáš Bednařík","t":"Litvínov","p":"U"},
  {"j":"Michal Gut","t":"Litvínov","p":"U"},
  {"j":"Martin Havelka","t":"Litvínov","p":"U"},
  {"j":"Josef Jícha","t":"Litvínov","p":"U"},
  {"j":"Ondřej Jurčík","t":"Litvínov","p":"U"},
  {"j":"David Kämpf","t":"Litvínov","p":"U"},
  {"j":"David Kaše","t":"Litvínov","p":"U"},
  {"j":"Ondřej Kaše","t":"Litvínov","p":"U"},
  {"j":"Petr Koblasa","t":"Litvínov","p":"U"},
  {"j":"Matěj Maštalířský","t":"Litvínov","p":"U"},
  {"j":"Jan Peroutka","t":"Litvínov","p":"U"},
  {"j":"Theodor Pištěk","t":"Litvínov","p":"U"},
  {"j":"Viktor Šámal","t":"Litvínov","p":"U"},
  {"j":"Jan Šprynar","t":"Litvínov","p":"U"},
  {"j":"Matúš Sukeľ","t":"Litvínov","p":"U"},
  {"j":"Tomáš Urban","t":"Litvínov","p":"U"},
  {"j":"Pawel Zygmunt","t":"Litvínov","p":"U"},
  {"j":"Malcolm Subban","t":"Pardubice","p":"B"},
  {"j":"Roman Will","t":"Pardubice","p":"B"},
  {"j":"Peter Čerešňák","t":"Pardubice","p":"O"},
  {"j":"Tomáš Dvořák","t":"Pardubice","p":"O"},
  {"j":"Daniel Gazda","t":"Pardubice","p":"O"},
  {"j":"Jan Košťálek","t":"Pardubice","p":"O"},
  {"j":"John Ludvig","t":"Pardubice","p":"O"},
  {"j":"Ondřej Mikliš","t":"Pardubice","p":"O"},
  {"j":"Miguël Tourigny","t":"Pardubice","p":"O"},
  {"j":"Roman Červenka","t":"Pardubice","p":"U"},
  {"j":"Samuel Hunter Fejes","t":"Pardubice","p":"U"},
  {"j":"Martin Kaut","t":"Pardubice","p":"U"},
  {"j":"Miloš Kelemen","t":"Pardubice","p":"U"},
  {"j":"Jáchym Kondelík","t":"Pardubice","p":"U"},
  {"j":"Jakub Lauko","t":"Pardubice","p":"U"},
  {"j":"Jan Mandát","t":"Pardubice","p":"U"},
  {"j":"Tomáš Nosek","t":"Pardubice","p":"U"},
  {"j":"Patrik Poulíček","t":"Pardubice","p":"U"},
  {"j":"Lukáš Sedlák","t":"Pardubice","p":"U"},
  {"j":"Jiří Smejkal","t":"Pardubice","p":"U"},
  {"j":"Vladimír Sobotka","t":"Pardubice","p":"U"},
  {"j":"Matěj Stránský","t":"Pardubice","p":"U"},
  {"j":"David Tomášek","t":"Pardubice","p":"U"},
  {"j":"Tomáš Vondráček","t":"Pardubice","p":"U"},
  {"j":"Nick Malík","t":"Plzeň","p":"B"},
  {"j":"Jan Růžička","t":"Plzeň","p":"B"},
  {"j":"Aleš Čech","t":"Plzeň","p":"O"},
  {"j":"Jakub Chromiak","t":"Plzeň","p":"O"},
  {"j":"Jakub Jeřábek","t":"Plzeň","p":"O"},
  {"j":"Dylan MacPherson","t":"Plzeň","p":"O"},
  {"j":"Daniel Malák","t":"Plzeň","p":"O"},
  {"j":"Igor Merezhko","t":"Plzeň","p":"O"},
  {"j":"Carter Robertson","t":"Plzeň","p":"O"},
  {"j":"Kristians Rubins","t":"Plzeň","p":"O"},
  {"j":"Matyáš Filip","t":"Plzeň","p":"U"},
  {"j":"Jan Fodor","t":"Plzeň","p":"U"},
  {"j":"Danny Katic","t":"Plzeň","p":"U"},
  {"j":"Christophe Lalancette","t":"Plzeň","p":"U"},
  {"j":"Jakub Lev","t":"Plzeň","p":"U"},
  {"j":"Adam Měchura","t":"Plzeň","p":"U"},
  {"j":"Mikko Petman","t":"Plzeň","p":"U"},
  {"j":"Ville Petman","t":"Plzeň","p":"U"},
  {"j":"Ondřej Pšenička","t":"Plzeň","p":"U"},
  {"j":"Ondřej Rohlík","t":"Plzeň","p":"U"},
  {"j":"Ivo Sedláček","t":"Plzeň","p":"U"},
  {"j":"Jan Schleiss","t":"Plzeň","p":"U"},
  {"j":"Dominik Simon","t":"Plzeň","p":"U"},
  {"j":"Lukáš Strnad","t":"Plzeň","p":"U"},
  {"j":"Michal Teplý","t":"Plzeň","p":"U"},
  {"j":"Adam Titlbach","t":"Plzeň","p":"U"},
  {"j":"Josef Kořenář","t":"Sparta Praha","p":"B"},
  {"j":"Jakub Kovář","t":"Sparta Praha","p":"B"},
  {"j":"Aaron Irving","t":"Sparta Praha","p":"O"},
  {"j":"Ronald Knot","t":"Sparta Praha","p":"O"},
  {"j":"Jakub Krejčík","t":"Sparta Praha","p":"O"},
  {"j":"Dominik Mašín","t":"Sparta Praha","p":"O"},
  {"j":"David Němeček","t":"Sparta Praha","p":"O"},
  {"j":"Mark Pysyk","t":"Sparta Praha","p":"O"},
  {"j":"Mikael Seppälä","t":"Sparta Praha","p":"O"},
  {"j":"Niko Seppälä","t":"Sparta Praha","p":"O"},
  {"j":"Jakub Sirota","t":"Sparta Praha","p":"O"},
  {"j":"Nino Tomov","t":"Sparta Praha","p":"O"},
  {"j":"Matěj Blümel","t":"Sparta Praha","p":"U"},
  {"j":"Marek Daníček","t":"Sparta Praha","p":"U"},
  {"j":"Martins Dzierkals","t":"Sparta Praha","p":"U"},
  {"j":"Roman Horák","t":"Sparta Praha","p":"U"},
  {"j":"Kryštof Hrabík","t":"Sparta Praha","p":"U"},
  {"j":"Ondřej Hrabík","t":"Sparta Praha","p":"U"},
  {"j":"Tomáš Hyka","t":"Sparta Praha","p":"U"},
  {"j":"Filip Chlapík","t":"Sparta Praha","p":"U"},
  {"j":"Pavel Kousal","t":"Sparta Praha","p":"U"},
  {"j":"Ondřej Najman","t":"Sparta Praha","p":"U"},
  {"j":"Jiří Pospíšil","t":"Sparta Praha","p":"U"},
  {"j":"Adam Raška","t":"Sparta Praha","p":"U"},
  {"j":"Michal Řepík","t":"Sparta Praha","p":"U"},
  {"j":"Jiří Sekáč","t":"Sparta Praha","p":"U"},
  {"j":"Devin Shore","t":"Sparta Praha","p":"U"},
  {"j":"Michael Špaček","t":"Sparta Praha","p":"U"},
  {"j":"Kristian Vesalainen","t":"Sparta Praha","p":"U"},
  {"j":"Ondřej Kacetl","t":"Třinec","p":"B"},
  {"j":"Marek Mazanec","t":"Třinec","p":"B"},
  {"j":"Marian Adámek","t":"Třinec","p":"O"},
  {"j":"David Aubrecht","t":"Třinec","p":"O"},
  {"j":"Jakub Galvas","t":"Třinec","p":"O"},
  {"j":"Patrik Koch","t":"Třinec","p":"O"},
  {"j":"Martin Marinčin","t":"Třinec","p":"O"},
  {"j":"David Musil","t":"Třinec","p":"O"},
  {"j":"Pavel Průšek","t":"Třinec","p":"O"},
  {"j":"Filip Pyrochta","t":"Třinec","p":"O"},
  {"j":"Marko Daňo","t":"Třinec","p":"U"},
  {"j":"Oscar Flynn","t":"Třinec","p":"U"},
  {"j":"Patrik Hrehorčák","t":"Třinec","p":"U"},
  {"j":"Libor Hudáček","t":"Třinec","p":"U"},
  {"j":"Petr Chlán","t":"Třinec","p":"U"},
  {"j":"Michal Kovařčík","t":"Třinec","p":"U"},
  {"j":"Ondřej Kovařčík","t":"Třinec","p":"U"},
  {"j":"Matěj Kubiesa","t":"Třinec","p":"U"},
  {"j":"Daniel Kurovský","t":"Třinec","p":"U"},
  {"j":"Andrej Nestrašil","t":"Třinec","p":"U"},
  {"j":"Miloš Roman","t":"Třinec","p":"U"},
  {"j":"Martin Růžička","t":"Třinec","p":"U"},
  {"j":"Daniel Voženílek","t":"Třinec","p":"U"},
  {"j":"Dominik Hrachovina","t":"Vítkovice","p":"B"},
  {"j":"Patrik Švančara","t":"Vítkovice","p":"B"},
  {"j":"Patrik Brůna","t":"Vítkovice","p":"O"},
  {"j":"Patrik Demel","t":"Vítkovice","p":"O"},
  {"j":"Alex Drábek","t":"Vítkovice","p":"O"},
  {"j":"Tomáš Herman","t":"Vítkovice","p":"O"},
  {"j":"Rhett Holland","t":"Vítkovice","p":"O"},
  {"j":"Samuel Kňažko","t":"Vítkovice","p":"O"},
  {"j":"Joseph Francis Leahy","t":"Vítkovice","p":"O"},
  {"j":"Mateusz Majkowski","t":"Vítkovice","p":"O"},
  {"j":"Tomáš Pavelka","t":"Vítkovice","p":"O"},
  {"j":"Vojtěch Port","t":"Vítkovice","p":"O"},
  {"j":"Tomáš Tomaškovič","t":"Vítkovice","p":"O"},
  {"j":"Josh Wesley","t":"Vítkovice","p":"O"},
  {"j":"Jakub Zbořil","t":"Vítkovice","p":"O"},
  {"j":"Jindřich Abdul","t":"Vítkovice","p":"U"},
  {"j":"Jan Bernovský","t":"Vítkovice","p":"U"},
  {"j":"David Cienciala","t":"Vítkovice","p":"U"},
  {"j":"Šimon Fasner","t":"Vítkovice","p":"U"},
  {"j":"Sebastian Glas","t":"Vítkovice","p":"U"},
  {"j":"Jan Hladonik","t":"Vítkovice","p":"U"},
  {"j":"Marek Hrivík","t":"Vítkovice","p":"U"},
  {"j":"Marek Kalus","t":"Vítkovice","p":"U"},
  {"j":"Filip Krivošík","t":"Vítkovice","p":"U"},
  {"j":"Krzysztof Macias","t":"Vítkovice","p":"U"},
  {"j":"Michael Nazad","t":"Vítkovice","p":"U"},
  {"j":"Anthony Nellis","t":"Vítkovice","p":"U"},
  {"j":"Dominik Petr","t":"Vítkovice","p":"U"},
  {"j":"Michal Šebesta","t":"Vítkovice","p":"U"},
  {"j":"Jan Šír","t":"Vítkovice","p":"U"},
  {"j":"Šimon Stránský","t":"Vítkovice","p":"U"},
  {"j":"Chad Yetman","t":"Vítkovice","p":"U"},
  {"j":"Matěj Žídek","t":"Vítkovice","p":"U"},
  {"j":"Dominik Furch","t":"Mladá Boleslav","p":"B"},
  {"j":"Vojtěch Mokry","t":"Mladá Boleslav","p":"B"},
  {"j":"Vojtěch Budík","t":"Mladá Boleslav","p":"O"},
  {"j":"Adam Martin Hlinský","t":"Mladá Boleslav","p":"O"},
  {"j":"Adam Jánošík","t":"Mladá Boleslav","p":"O"},
  {"j":"Karel Křepelka","t":"Mladá Boleslav","p":"O"},
  {"j":"Šimon Kubíček","t":"Mladá Boleslav","p":"O"},
  {"j":"David Moravec","t":"Mladá Boleslav","p":"O"},
  {"j":"Filip Pavlík","t":"Mladá Boleslav","p":"O"},
  {"j":"Martin Skärberg","t":"Mladá Boleslav","p":"O"},
  {"j":"Adam Vlasák","t":"Mladá Boleslav","p":"O"},
  {"j":"Vojtěch Vochvest","t":"Mladá Boleslav","p":"O"},
  {"j":"Petr Zámorský","t":"Mladá Boleslav","p":"O"},
  {"j":"Jan Buchtele","t":"Mladá Boleslav","p":"U"},
  {"j":"Tomáš Fořt","t":"Mladá Boleslav","p":"U"},
  {"j":"Matěj Gardoň","t":"Mladá Boleslav","p":"U"},
  {"j":"Felikss Gavars","t":"Mladá Boleslav","p":"U"},
  {"j":"Dávid Gríger","t":"Mladá Boleslav","p":"U"},
  {"j":"Vojtěch Hradec","t":"Mladá Boleslav","p":"U"},
  {"j":"Steven Jandric","t":"Mladá Boleslav","p":"U"},
  {"j":"Radek Koblížek","t":"Mladá Boleslav","p":"U"},
  {"j":"Patrik Král","t":"Mladá Boleslav","p":"U"},
  {"j":"Dominik Lakatoš","t":"Mladá Boleslav","p":"U"},
  {"j":"Jakub Lichtag","t":"Mladá Boleslav","p":"U"},
  {"j":"Vojtěch Malínek","t":"Mladá Boleslav","p":"U"},
  {"j":"Jordan Martel","t":"Mladá Boleslav","p":"U"},
  {"j":"Imrich Maxin","t":"Mladá Boleslav","p":"U"},
  {"j":"Antoine Morand","t":"Mladá Boleslav","p":"U"},
  {"j":"Aleksi Rekonen","t":"Mladá Boleslav","p":"U"},
  {"j":"Pavol Skalický","t":"Mladá Boleslav","p":"U"},
  {"j":"Jan Závora","t":"Mladá Boleslav","p":"U"},
  {"j":"Oldřich Cichoň","t":"Olomouc","p":"B"},
  {"j":"Matěj Machovský","t":"Olomouc","p":"B"},
  {"j":"Tomáš Černý","t":"Olomouc","p":"O"},
  {"j":"Trevor Cosgrove","t":"Olomouc","p":"O"},
  {"j":"Petr Gewiese","t":"Olomouc","p":"O"},
  {"j":"Michal Hrádek","t":"Olomouc","p":"O"},
  {"j":"Marek Chvátal","t":"Olomouc","p":"O"},
  {"j":"Jiří Ondrušek","t":"Olomouc","p":"O"},
  {"j":"Patriks Ozols","t":"Olomouc","p":"O"},
  {"j":"Rayen Petrovický","t":"Olomouc","p":"O"},
  {"j":"Alex Rašner","t":"Olomouc","p":"O"},
  {"j":"Dalibor Řezníček","t":"Olomouc","p":"O"},
  {"j":"Adam Rutar","t":"Olomouc","p":"O"},
  {"j":"Evan Stella","t":"Olomouc","p":"O"},
  {"j":"Lukáš Anděl","t":"Olomouc","p":"U"},
  {"j":"Carl Berglund","t":"Olomouc","p":"U"},
  {"j":"Daniel Herčík","t":"Olomouc","p":"U"},
  {"j":"Jakub Kos","t":"Olomouc","p":"U"},
  {"j":"Rok Macuh","t":"Olomouc","p":"U"},
  {"j":"Joshua James Mácha","t":"Olomouc","p":"U"},
  {"j":"Ondřej Matýs","t":"Olomouc","p":"U"},
  {"j":"Daniel Ministr","t":"Olomouc","p":"U"},
  {"j":"Jakub Navrátil","t":"Olomouc","p":"U"},
  {"j":"Jakub Orsava","t":"Olomouc","p":"U"},
  {"j":"Karel Plášek","t":"Olomouc","p":"U"},
  {"j":"Zach Senyshyn","t":"Olomouc","p":"U"},
  {"j":"Matúš Spodniak","t":"Olomouc","p":"U"},
  {"j":"Martin Štohanzl","t":"Olomouc","p":"U"},
  {"j":"Michal Tomeček","t":"Olomouc","p":"U"},
  {"j":"David Vitouch","t":"Olomouc","p":"U"},
  {"j":"Michal Vitouch","t":"Olomouc","p":"U"},
  {"j":"Jan Kavan","t":"Kometa Brno","p":"B"},
  {"j":"Eugen Rabčan","t":"Kometa Brno","p":"B"},
  {"j":"Aleš Stezka","t":"Kometa Brno","p":"B"},
  {"j":"Tadeáš Beroun","t":"Kometa Brno","p":"O"},
  {"j":"Michal Gulaši","t":"Kometa Brno","p":"O"},
  {"j":"Filip Král","t":"Kometa Brno","p":"O"},
  {"j":"Radek Kučeřík","t":"Kometa Brno","p":"O"},
  {"j":"Dalimil Mikyska","t":"Kometa Brno","p":"O"},
  {"j":"Richard Nedomlel","t":"Kometa Brno","p":"O"},
  {"j":"Jan Ščotka","t":"Kometa Brno","p":"O"},
  {"j":"Stanislav Svozil","t":"Kometa Brno","p":"O"},
  {"j":"Luke Witkowski","t":"Kometa Brno","p":"O"},
  {"j":"Libor Zábranský","t":"Kometa Brno","p":"O"},
  {"j":"Jakub Zubíček","t":"Kometa Brno","p":"O"},
  {"j":"Jakub Brabenec","t":"Kometa Brno","p":"U"},
  {"j":"Maxim Čajkovič","t":"Kometa Brno","p":"U"},
  {"j":"Lukáš Cingel","t":"Kometa Brno","p":"U"},
  {"j":"Jan Ekrt","t":"Kometa Brno","p":"U"},
  {"j":"Jakub Flek","t":"Kometa Brno","p":"U"},
  {"j":"Michal Hartl","t":"Kometa Brno","p":"U"},
  {"j":"Danny Chludil","t":"Kometa Brno","p":"U"},
  {"j":"Arttu Ilomäki","t":"Kometa Brno","p":"U"},
  {"j":"Andrej Kollár","t":"Kometa Brno","p":"U"},
  {"j":"Michal Kunc","t":"Kometa Brno","p":"U"},
  {"j":"Silvester Kusko","t":"Kometa Brno","p":"U"},
  {"j":"Robert Leino","t":"Kometa Brno","p":"U"},
  {"j":"David Moravec","t":"Kometa Brno","p":"U"},
  {"j":"Kristián Pospíšil","t":"Kometa Brno","p":"U"},
  {"j":"Tomáš Selič","t":"Kometa Brno","p":"U"},
  {"j":"Jan Süss","t":"Kometa Brno","p":"U"},
  {"j":"Maxim Vehovský","t":"Kometa Brno","p":"U"},
  {"j":"Adam Zbořil","t":"Kometa Brno","p":"U"},
  {"j":"Hynek Zohorna","t":"Kometa Brno","p":"U"},
  {"j":"Tomáš Zohorna","t":"Kometa Brno","p":"U"},
  {"j":"Stanislav Škorvánek","t":"Mountfield HK","p":"B"},
  {"j":"Tomáš Vomáčka","t":"Mountfield HK","p":"B"},
  {"j":"Štěpán Černý","t":"Mountfield HK","p":"O"},
  {"j":"Petr Kalina","t":"Mountfield HK","p":"O"},
  {"j":"Anders Koch","t":"Mountfield HK","p":"O"},
  {"j":"Graeme McCormack","t":"Mountfield HK","p":"O"},
  {"j":"T.J. Melancon","t":"Mountfield HK","p":"O"},
  {"j":"Dávid Mudrák","t":"Mountfield HK","p":"O"},
  {"j":"Radek Pilař","t":"Mountfield HK","p":"O"},
  {"j":"Martin Pláněk","t":"Mountfield HK","p":"O"},
  {"j":"David Sýkora","t":"Mountfield HK","p":"O"},
  {"j":"Michael Gabriel Vukojevic","t":"Mountfield HK","p":"O"},
  {"j":"Connor Dave Bunnaman","t":"Mountfield HK","p":"U"},
  {"j":"Viliam Čacho","t":"Mountfield HK","p":"U"},
  {"j":"Aleš Jergl","t":"Mountfield HK","p":"U"},
  {"j":"Kevin Klíma","t":"Mountfield HK","p":"U"},
  {"j":"Martin Kohout","t":"Mountfield HK","p":"U"},
  {"j":"Robert Kousal","t":"Mountfield HK","p":"U"},
  {"j":"Patrik Miškář","t":"Mountfield HK","p":"U"},
  {"j":"Markus Nenonen","t":"Mountfield HK","p":"U"},
  {"j":"Dominik Pavlík","t":"Mountfield HK","p":"U"},
  {"j":"Radovan Pavlík","t":"Mountfield HK","p":"U"},
  {"j":"Jordann Perret","t":"Mountfield HK","p":"U"},
  {"j":"Lukáš Radil","t":"Mountfield HK","p":"U"},
  {"j":"Alex Tamáši","t":"Mountfield HK","p":"U"},
  {"j":"Jan Vyvial","t":"Mountfield HK","p":"U"},
  {"j":"Patrik Zdráhal","t":"Mountfield HK","p":"U"},
  {"j":"Milan Klouček","t":"České Budějovice","p":"B"},
  {"j":"Jan Strmeň","t":"České Budějovice","p":"B"},
  {"j":"Ondřej Kachyňa","t":"České Budějovice","p":"O"},
  {"j":"Tomáš Kundrátek","t":"České Budějovice","p":"O"},
  {"j":"Lucas Nordsäter","t":"České Budějovice","p":"O"},
  {"j":"Pavel Pýcha","t":"České Budějovice","p":"O"},
  {"j":"Jan Štencel","t":"České Budějovice","p":"O"},
  {"j":"Ondřej Vála","t":"České Budějovice","p":"O"},
  {"j":"Roman Vráblík","t":"České Budějovice","p":"O"},
  {"j":"Filip Ahl","t":"České Budějovice","p":"U"},
  {"j":"Parker Bell","t":"České Budějovice","p":"U"},
  {"j":"Martin Beránek","t":"České Budějovice","p":"U"},
  {"j":"Michal Bulíř","t":"České Budějovice","p":"U"},
  {"j":"Samuel Drančák","t":"České Budějovice","p":"U"},
  {"j":"Štěpán Hoch","t":"České Budějovice","p":"U"},
  {"j":"Matyáš Humeník","t":"České Budějovice","p":"U"},
  {"j":"Tomáš Chlubna","t":"České Budějovice","p":"U"},
  {"j":"Josef Koláček","t":"České Budějovice","p":"U"},
  {"j":"Renars Krastenbergs","t":"České Budějovice","p":"U"},
  {"j":"Róbert Lantoši","t":"České Budějovice","p":"U"},
  {"j":"Jakub Lev","t":"České Budějovice","p":"U"},
  {"j":"Pavel Novák","t":"České Budějovice","p":"U"},
  {"j":"Nick Olesen","t":"České Budějovice","p":"U"},
  {"j":"Jan Ordoš","t":"České Budějovice","p":"U"},
  {"j":"Jakub Pour","t":"České Budějovice","p":"U"},
  {"j":"Matěj Toman","t":"České Budějovice","p":"U"},
  {"j":"Marek Zachar","t":"České Budějovice","p":"U"}
  ]
};
